version: "3.9"

services:
  postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=yurii
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
  server:
    build: .
    command: python3 app.py
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:admin@postgres_db:5432/yurii
      - SQL_HOST=postgres_db
      - SQL_PORT=5432
      - PORT=8080
    restart: unless-stopped
    ports:
      - "5000:8080"
    depends_on:
      - postgres_db