FROM python:3.8-slim

WORKDIR /usr/src/app

COPY requirements.txt .

RUN \
    apk add --no-cache tesseract-ocr python3 py3-numpy postgresql-libs && \
    pip3 install --upgrade pip setuptools wheel && \
    apk add --no-cache --virtual .build-deps gcc g++ zlib-dev make python3-dev py-numpy-dev jpeg-dev musl-dev postgresql-dev && \
    python3 -m pip install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps

COPY . .

CMD ["python3", "app.py"]